apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: IMAGE
    type: string
    description: IMAGE to be build from the code
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository

  - name: image-scan
    taskRef:
      name: rox-image-scan
      kind: ClusterTask
    params:
    - name: image
      value: $(params.IMAGE)@$(tasks.build-image.results.IMAGE_DIGEST)
    - name: rox_api_token
      value: roxsecrets
    - name: rox_central_endpoint
      value: roxsecrets
    - name: output_format
      value: pretty
    runAfter:
    - build-image
  - name: image-check
    taskRef:
      name: rox-image-check
      kind: ClusterTask
    params:
    - name: image
      value: $(params.IMAGE)@$(tasks.build-image.results.IMAGE_DIGEST)
    - name: rox_api_token
      value: roxsecrets
    - name: rox_central_endpoint
      value: roxsecrets
    runAfter:
    - build-image

  - name: apply-manifests
    taskRef:
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - image-scan
    - image-check
  - name: update-deployment
    taskRef:
      name: update-deployment
    params:
    - name: deployment
      value: $(params.deployment-name)
    - name: IMAGE
      value: $(params.IMAGE)@$(tasks.build-image.results.IMAGE_DIGEST)
    runAfter:
    - apply-manifests
